In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('editors-output-2018-09-09.csv')

In [18]:
df.columns

Index(['Key', 'Authorized Name', 'Author Name English', 'Author Name Latin',
       'Perseus Name', 'Time Period', 'Author Birth Date', 'Author Death Date',
       'Floruit/Active', 'Ancient Geographic Identity',
       'Modern Geographic Identity', 'LoC Name', 'LoC ID', 'LoC Source: URL',
       'LofC URI: URL', 'PHI Number', 'Stoa Number', 'VIAF ID',
       'VIAF Source: URL', 'BNE Name', 'BNE URL', 'BNF Name', 'BNF URL',
       'DNB Name', 'DNB URL', 'ICCU Name', 'ICCU URL', 'ISNI Name', 'ISNI URL',
       'Wikidata URL', 'Wikipedia URL', 'WorldCat Identity URL'],
      dtype='object')

In [19]:
df2 = pd.DataFrame(df['Authorized Name'].apply(lambda x: str(x).split(', ')))

In [20]:
df2

                                       Authorized Name
0         [Gronovius, Laurentius Theodorus, 1730-1777]
1                            [Diehl, Ernst, 1874-1947]
2                         [Logus, Georgius, 1484-1553]
3                     [Meurs, Johannes van, 1579-1639]
4    [Philippe de Prétot, Étienne-André, 1710-1787]
5                  [Spalding, Georg Ludvig, 1762-1811]
6       [Eisenschmidt, Christian Friedrich, 1763-1827]
7                            [Tollius, Jacobus, -1696]
8                    [Frigell, A. (Anders), 1820-1897]
9            [Gaasbeeck, Daniel van, active 1655-1692]
10                              [Maire, Joannes 1576-]
11               [Ruperti, Georg Alexander, 1758-1839]
12                        [Enk, Petrus Joannes, 1885-]
13                      [Agustín, Antonio, 1517-1586]
14                     [Zinzerling, Jean, 1580?-1620?]
15                            [Du Ryer, Pierre, -1658]
16               [Dübner, Fr. (Friedrich), 1802-1867]
17                    [Blankaart, Nikolaas, 1624-1703]
18                       [Schroeter, Friedrich, -1746]
19                    [Valpy, Abraham John, 1787-1854]
20    [Kelsey, Francis W. (Francis Willey), 1858-1927]
21                       [Wagener, Auguste, 1829-1896]
22                  [Hesselius, Franciscus, 1680-1746]
23                 [Ernesti, Johann August, 1707-1781]
24                      [Hooghe, Romeyn de, 1645-1708]
25                         [Sillig, Julius, 1801-1855]
26           [Hoeve, Willem van der, active 1639-1685]
27                      [Modius, François, 1556-1597]
28               [Escribano, Alonso, active 1567-1577]
29             [Graevius, Joannes Georgius, 1632-1703]
..                                                 ...
151                           [Caius, John, 1510-1573]
152                           [Carey, John, 1756-1826]
153                       [Ellis, Robinson, 1834-1913]
154                        [Chacón, Pedro, 1527-1581]
155                       [Vettori, Pietro, 1499-1585]
156              [Raphelengius, Franciscus, 1539-1597]
157    [Ernesti, Johann Christian Gottlieb, 1756-1802]
158                         [Dederich, Andreas, 1804-]
159            [Herbermann, Charles George, 1840-1916]
160                      [Turnèbe, Adrien, 1512-1565]
161                        [Riguez, Robert, 1647-1725]
162                  [Lindenbrog, Heinrich, 1570-1642]
163                         [Titi, Roberto, 1551-1609]
164                   [Opsopäus, Johannes, 1556-1596]
165                          [Clarke, John, 1687-1734]
166              [Gruner, Johann Friedrich, 1723-1778]
167                         [Oehler, Franz, 1817-1866]
168                     [Cesariano, Cesare, 1483-1543]
169                      [Krahner, Leopold, 1810-1884]
170                          [Krohn, Fritz, 1873-1941]
171       [Breysig, Alfred August Bernhard, 1831-1901]
172                    [Freinsheim, Johann, 1608-1660]
173                       [Bassi, Domenico, 1859-1942]
174                     [Faerno, Gabriello, 1511-1561]
175                     [Schottus, Andreas, 1552-1629]
176                               [Frick, Karl, 1848-]
177                     [Kohlmann, Philipp, 1842-1889]
178                    [Maittaire, Michael, 1667-1747]
179             [Poolsum, Jacob van, active 1701-1762]
180            [Gaasbeeck, Abraham van fl., 1655-1675]

[181 rows x 1 columns]

In [21]:
df3 = pd.DataFrame(df2['Authorized Name'].values.tolist(),columns=['name1','name2','date'])

In [22]:
df3.columns

Index(['name1', 'name2', 'date'], dtype='object')

In [23]:
df3

                   name1                        name2              date
0              Gronovius         Laurentius Theodorus         1730-1777
1                  Diehl                        Ernst         1874-1947
2                  Logus                     Georgius         1484-1553
3                  Meurs                 Johannes van         1579-1639
4    Philippe de Prétot              Étienne-André         1710-1787
5               Spalding                 Georg Ludvig         1762-1811
6           Eisenschmidt          Christian Friedrich         1763-1827
7                Tollius                      Jacobus             -1696
8                Frigell                  A. (Anders)         1820-1897
9              Gaasbeeck                   Daniel van  active 1655-1692
10                 Maire                Joannes 1576-              None
11               Ruperti              Georg Alexander         1758-1839
12                   Enk               Petrus Joannes             1885-
13              Agustín                      Antonio         1517-1586
14            Zinzerling                         Jean       1580?-1620?
15               Du Ryer                       Pierre             -1658
16               Dübner              Fr. (Friedrich)         1802-1867
17             Blankaart                     Nikolaas         1624-1703
18             Schroeter                    Friedrich             -1746
19                 Valpy                 Abraham John         1787-1854
20                Kelsey  Francis W. (Francis Willey)         1858-1927
21               Wagener                      Auguste         1829-1896
22             Hesselius                   Franciscus         1680-1746
23               Ernesti                Johann August         1707-1781
24                Hooghe                    Romeyn de         1645-1708
25                Sillig                       Julius         1801-1855
26                 Hoeve               Willem van der  active 1639-1685
27                Modius                    François         1556-1597
28             Escribano                       Alonso  active 1567-1577
29              Graevius             Joannes Georgius         1632-1703
..                   ...                          ...               ...
151                Caius                         John         1510-1573
152                Carey                         John         1756-1826
153                Ellis                     Robinson         1834-1913
154              Chacón                        Pedro         1527-1581
155              Vettori                       Pietro         1499-1585
156         Raphelengius                   Franciscus         1539-1597
157              Ernesti    Johann Christian Gottlieb         1756-1802
158             Dederich                      Andreas             1804-
159           Herbermann               Charles George         1840-1916
160             Turnèbe                       Adrien         1512-1565
161               Riguez                       Robert         1647-1725
162           Lindenbrog                     Heinrich         1570-1642
163                 Titi                      Roberto         1551-1609
164            Opsopäus                     Johannes         1556-1596
165               Clarke                         John         1687-1734
166               Gruner             Johann Friedrich         1723-1778
167               Oehler                        Franz         1817-1866
168            Cesariano                       Cesare         1483-1543
169              Krahner                      Leopold         1810-1884
170                Krohn                        Fritz         1873-1941
171              Breysig       Alfred August Bernhard         1831-1901
172           Freinsheim                       Johann         1608-1660
173                Bassi                     Domenico         1859-1942
174               Faerno                    Gabriello         1511-1561
175             Schottus                      Andreas         1552-1629
176                Frick                         Karl             1848-
177             Kohlmann                      Philipp         1842-1889
178            Maittaire                      Michael         1667-1747
179              Poolsum                    Jacob van  active 1701-1762
180            Gaasbeeck              Abraham van fl.         1655-1675

[181 rows x 3 columns]

In [24]:
df4 = pd.DataFrame(df3['date'].apply(lambda x: str(x).split('-')),columns=['date'])

In [25]:
df4

                    date
0           [1730, 1777]
1           [1874, 1947]
2           [1484, 1553]
3           [1579, 1639]
4           [1710, 1787]
5           [1762, 1811]
6           [1763, 1827]
7               [, 1696]
8           [1820, 1897]
9    [active 1655, 1692]
10                [None]
11          [1758, 1839]
12              [1885, ]
13          [1517, 1586]
14        [1580?, 1620?]
15              [, 1658]
16          [1802, 1867]
17          [1624, 1703]
18              [, 1746]
19          [1787, 1854]
20          [1858, 1927]
21          [1829, 1896]
22          [1680, 1746]
23          [1707, 1781]
24          [1645, 1708]
25          [1801, 1855]
26   [active 1639, 1685]
27          [1556, 1597]
28   [active 1567, 1577]
29          [1632, 1703]
..                   ...
151         [1510, 1573]
152         [1756, 1826]
153         [1834, 1913]
154         [1527, 1581]
155         [1499, 1585]
156         [1539, 1597]
157         [1756, 1802]
158             [1804, ]
159         [1840, 1916]
160         [1512, 1565]
161         [1647, 1725]
162         [1570, 1642]
163         [1551, 1609]
164         [1556, 1596]
165         [1687, 1734]
166         [1723, 1778]
167         [1817, 1866]
168         [1483, 1543]
169         [1810, 1884]
170         [1873, 1941]
171         [1831, 1901]
172         [1608, 1660]
173         [1859, 1942]
174         [1511, 1561]
175         [1552, 1629]
176             [1848, ]
177         [1842, 1889]
178         [1667, 1747]
179  [active 1701, 1762]
180         [1655, 1675]

[181 rows x 1 columns]

In [26]:
df4 = pd.DataFrame(df4['date'].values.tolist(),columns=['bdate','ddate'])

In [27]:
df4

           bdate  ddate
0           1730   1777
1           1874   1947
2           1484   1553
3           1579   1639
4           1710   1787
5           1762   1811
6           1763   1827
7                  1696
8           1820   1897
9    active 1655   1692
10          None   None
11          1758   1839
12          1885
13          1517   1586
14         1580?  1620?
15                 1658
16          1802   1867
17          1624   1703
18                 1746
19          1787   1854
20          1858   1927
21          1829   1896
22          1680   1746
23          1707   1781
24          1645   1708
25          1801   1855
26   active 1639   1685
27          1556   1597
28   active 1567   1577
29          1632   1703
..           ...    ...
151         1510   1573
152         1756   1826
153         1834   1913
154         1527   1581
155         1499   1585
156         1539   1597
157         1756   1802
158         1804
159         1840   1916
160         1512   1565
161         1647   1725
162         1570   1642
163         1551   1609
164         1556   1596
165         1687   1734
166         1723   1778
167         1817   1866
168         1483   1543
169         1810   1884
170         1873   1941
171         1831   1901
172         1608   1660
173         1859   1942
174         1511   1561
175         1552   1629
176         1848
177         1842   1889
178         1667   1747
179  active 1701   1762
180         1655   1675

[181 rows x 2 columns]

In [28]:
df5 = pd.concat([df3,df4], axis=1, sort=False)

In [29]:
df5

,name1,name2,date,bdate,ddate
0,Gronovius,Laurentius Theodorus,1730-1777,1730,1777
1,Diehl,Ernst,1874-1947,1874,1947
2,Logus,Georgius,1484-1553,1484,1553
3,Meurs,Johannes van,1579-1639,1579,1639
4,Philippe de Prétot,Étienne-André,1710-1787,1710,1787
5,Spalding,Georg Ludvig,1762-1811,1762,1811
6,Eisenschmidt,Christian Friedrich,1763-1827,1763,1827
7,Tollius,Jacobus,-1696,,1696
8,Frigell,A. (Anders),1820-1897,1820,1897
9,Gaasbeeck,Daniel van,active 1655-1692,active 1655,1692
10,Maire,Joannes 1576-,None,None,None
11,Ruperti,Georg Alexander,1758-1839,1758,1839
12,Enk,Petrus Joannes,1885-,1885,
13,Agustín,Antonio,1517-1586,1517,1586
14,Zinzerling,Jean,1580?-1620?,1580?,1620?
15,Du Ryer,Pierre,-1658,,1658
16,Dübner,Fr. (Friedrich),1802-1867,1802,1867
17,Blankaart,Nikolaas,1624-1703,1624,1703
18,Schroeter,Friedrich,-1746,,1746
19,Valpy,Abraham John,1787-1854,1787,1854
20,Kelsey,Francis W. (Francis Willey),1858-1927,1858,1927
21,Wagener,Auguste,1829-1896,1829,1896
22,Hesselius,Franciscus,1680-1746,1680,1746
23,Ernesti,Johann August,1707-1781,1707,1781
24,Hooghe,Romeyn de,1645-1708,1645,1708
25,Sillig,Julius,1801-1855,1801,1855
26,Hoeve,Willem van der,active 1639-1685,active 1639,1685
27,Modius,François,1556-1597,1556,1597
28,Escribano,Alonso,active 1567-1577,active 1567,1577
29,Graevius,Joannes Georgius,1632-1703,1632,1703
...,...,...,...,...,...
151,Caius,John,1510-1573,1510,1573
152,Carey,John,1756-1826,1756,1826
153,Ellis,Robinson,1834-1913,1834,1913
154,Chacón,Pedro,1527-1581,1527,1581
155,Vettori,Pietro,1499-1585,1499,1585
156,Raphelengius,Franciscus,1539-1597,1539,1597
157,Ernesti,Johann Christian Gottlieb,1756-1802,1756,1802
158,Dederich,Andreas,1804-,1804,
159,Herbermann,Charles George,1840-1916,1840,1916
160,Turnèbe,Adrien,1512-1565,1512,1565
161,Riguez,Robert,1647-1725,1647,1725
162,Lindenbrog,Heinrich,1570-1642,1570,1642
163,Titi,Roberto,1551-1609,1551,1609
164,Opsopäus,Johannes,1556-1596,1556,1596
165,Clarke,John,1687-1734,1687,1734
166,Gruner,Johann Friedrich,1723-1778,1723,1778
167,Oehler,Franz,1817-1866,1817,1866
168,Cesariano,Cesare,1483-1543,1483,1543
169,Krahner,Leopold,1810-1884,1810,1884
170,Krohn,Fritz,1873-1941,1873,1941
171,Breysig,Alfred August Bernhard,1831-1901,1831,1901
172,Freinsheim,Johann,1608-1660,1608,1660
173,Bassi,Domenico,1859-1942,1859,1942
174,Faerno,Gabriello,1511-1561,1511,1561
175,Schottus,Andreas,1552-1629,1552,1629
176,Frick,Karl,1848-,1848,
177,Kohlmann,Philipp,1842-1889,1842,1889
178,Maittaire,Michael,1667-1747,1667,1747
179,Poolsum,Jacob van,active 1701-1762,active 1701,1762
180,Gaasbeeck,Abraham van fl.,1655-1675,1655,1675

In [30]:
df5.to_csv('editors-dates-output-2018-09-09.csv')